In [15]:
import os
import torch
import numpy as np
from torch.utils.data import Dataset, DataLoader

In [16]:
class FilterDataset(Dataset):
    def __init__(self):
        ...

    def __len__(self):
        return 10

    def __getitem__(self, idx):
        return idx

In [17]:
filter_dataset = FilterDataset()

In [18]:
filter_dataloader = DataLoader(filter_dataset, batch_size=2, shuffle=True)

In [14]:
for i in range(len(filter_dataset)):
    sample = filter_dataset[i]

    print(sample)

0
1
2
3
4
5
6
7
8
9


In [25]:
filter_dataloader

In [29]:
for sample in filter_dataloader:

    print(sample)

tensor([5, 4])
tensor([7, 0])
tensor([3, 1])
tensor([8, 2])
tensor([6, 9])
