# Data File Check

- data_splits.pickle
- id_to_ix_map.pickle
- token_counts.pickle

## data_splits.pickle

In [10]:
import pickle

def get_fold_data():
    with open('../data_file/data_splits.pickle', 'rb') as f:
        data_splits = pickle.load(f)
    return data_splits

data_splits = get_fold_data()

In [2]:
for key1 in data_splits.keys():
    for key2 in data_splits[key1].keys():
        for key3 in data_splits[key1][key2].keys():
            count = 0
            for fold, values in enumerate(data_splits[key1][key2][key3]):
                fold_id_list = []
                for value in values:
                    fold_id_list.append(value)
                count += len(fold_id_list)

In [13]:
data_splits[0][250]['normed']

[['4BB5ADD5A1FE',
  'F789157CB6E6',
  '86BB3D5BA612',
  '738E215A237A',
  '34C7B34F1AE7',
  'E0FAD617D3BF',
  '27681E4EB137',
  'C0916625AAB0',
  '3F1900C42C55',
  'E046108929C0',
  'B56ABAADC95A',
  '060CD5A52BC6',
  '67E2D82B7387',
  'CBC776495BE0',
  'CFCB9135F1BF',
  '9C2E6F09CC73',
  '3F15318ECD44',
  '310355544D30',
  '603108B7285B',
  'F8EBE7994672',
  '60204ED9F4ED',
  '2114A12D2095',
  'C36AECC3C173',
  '541CC72DE4AE',
  'F20C7101F09D',
  '7CCF17D975F4',
  'BB27E087BE9E',
  'DC1DA01985EF',
  '86B3DB69F45F',
  'FBE13E9A446C',
  '5EF70094623C',
  '842888D759E2',
  '89039D21E960',
  '7CC5C392BF5C',
  'ED321E901AC7',
  '786C86C9ACFE',
  '160A9BD312B0',
  '886B98C32CAC',
  'D784E06655CB',
  '706F6F7F5612',
  '333F2F63BAE4',
  'BAC82DBE66F6',
  '4171CB7DF807',
  '8D7CBF2251F1',
  'D0432DB2D3A3',
  'E2A9D1243AF9',
  'E264A3F27D5C',
  'B98AD566DC48',
  'B9E9DC1D176F',
  '9C8126B25A26',
  '8B4BBB3F601D',
  'F891A929A12D',
  '7748D6B51DD8',
  '9A7185123048',
  '83998F1D3F9F',
  '5C66CBD

In [17]:
id_to_ix_map = {x.split('/')[-1].split('.')[0]: y for x, y in map_data.items()}


In [18]:
id_to_ix_map

{'CF48D9415493': 0,
 '9741E87BE7CE': 1,
 '43B24ED85767': 2,
 '7C898E56E23C': 3,
 'EB9D8FFB4F45': 4,
 'F45F03EBB2CA': 5,
 '75BD2CB94662': 6,
 '5FB75CCB31F8': 7,
 '46527BA000FB': 8,
 '16585724607E': 9,
 '4434757F78FB': 10,
 '9FD65F435FD4': 11,
 '0F10DC1AE015': 12,
 '1A4DFD122114': 13,
 'D12A571CCFA4': 14,
 '4D04E578034E': 15,
 'D1DBB999DB47': 16,
 'B78FDCCC587F': 17,
 'F2725AAFA685': 18,
 '0A5299390319': 19,
 'D9C99C58FDA5': 20,
 '31DDE751E2BD': 21,
 '202A2848311C': 22,
 'A60D3B8ABD92': 23,
 'BEBB31733A38': 24,
 'F0E76CC2EF7A': 25,
 '4B9F8C01BFA1': 26,
 'D72B8EA15C83': 27,
 '0DBE82E9933F': 28,
 '8A745CBCD81E': 29,
 '3109DD806F4D': 30,
 '446C81F7D0B7': 31,
 'B64B9CDA1E54': 32,
 '287F79B6D6F6': 33,
 'E92185894096': 34,
 '5CE0853A33EB': 35,
 '1D7EEE65F780': 36,
 '019328A0D7A3': 37,
 '5942FB27D5C3': 38,
 '849BE041D1C8': 39,
 'B111395C3C6E': 40,
 '11CE345BAEF2': 41,
 'D265C0C54BDC': 42,
 'DC55E9D28966': 43,
 'CC4A42F9E5A1': 44,
 'F4FD84517F40': 45,
 'AADCE1E62CE7': 46,
 'E84CD172D3EA': 47,
 '

## id_to_ix_map.pickle

In [14]:
with open('../data_file/id_to_ix_map.pickle', 'rb') as f:
    map_data = pickle.load(f)

In [9]:
map_data

{'../../../feedback-prize-2021/train/CF48D9415493.txt': 0,
 '../../../feedback-prize-2021/train/9741E87BE7CE.txt': 1,
 '../../../feedback-prize-2021/train/43B24ED85767.txt': 2,
 '../../../feedback-prize-2021/train/7C898E56E23C.txt': 3,
 '../../../feedback-prize-2021/train/EB9D8FFB4F45.txt': 4,
 '../../../feedback-prize-2021/train/F45F03EBB2CA.txt': 5,
 '../../../feedback-prize-2021/train/75BD2CB94662.txt': 6,
 '../../../feedback-prize-2021/train/5FB75CCB31F8.txt': 7,
 '../../../feedback-prize-2021/train/46527BA000FB.txt': 8,
 '../../../feedback-prize-2021/train/16585724607E.txt': 9,
 '../../../feedback-prize-2021/train/4434757F78FB.txt': 10,
 '../../../feedback-prize-2021/train/9FD65F435FD4.txt': 11,
 '../../../feedback-prize-2021/train/0F10DC1AE015.txt': 12,
 '../../../feedback-prize-2021/train/1A4DFD122114.txt': 13,
 '../../../feedback-prize-2021/train/D12A571CCFA4.txt': 14,
 '../../../feedback-prize-2021/train/4D04E578034E.txt': 15,
 '../../../feedback-prize-2021/train/D1DBB999DB47.

## token_counts.pickle

In [ ]:
import h5py
import numpy as np
from tqdm import tqdm

In [ ]:
total_token_counts = np.zeros(15, 'f8')
raw_token_counts = np.zeros(15, 'f8')
for x, y in sorted_counters:
    raw_token_counts[x] = y
    if x == 0:
        total_token_counts[0] = y
    else:
        ix = (x + 1) // 2 * 2
        total_token_counts[ix] += y total_token_counts[ix - 1] += y

raw_token_counts /= raw_token_counts.mean()

In [ ]:
f = h5py.File('../../processed_data_v0.h5py')

all_token_counts = np.zeros((15,), 'i8')

for ix in tqdm(range(len(f['tokens']) - 1)):
    targets = f['cbio_labels'][ix].argmax(-1)[1:f['num_tokens'][ix][0] - 1]
    a, b = np.unique(targets, return_counts=True)
    all_token_counts[a] += b
    
    ungroupped_token_counts = all_token_counts / all_token_counts.mean()

In [5]:
with open('../data_file/token_counts.pickle', 'rb') as f:
    groupped_token_counts, ungroupped_token_counts = pickle.load(f)

In [7]:
ungroupped_token_counts

array([ 549185.,    9305.,  551937.,   15419.,  302404.,   45702.,
       4023777.,   50206.,  932022.,   13505.,  931556.,    5817.,
        151710.,    4337.,  133918.])

In [9]:
groupped_token_counts

array([ 549185.,  561242.,  561242.,  317823.,  317823., 4069479.,
       4069479.,  982228.,  982228.,  945061.,  945061.,  157527.,
        157527.,  138255.,  138255.])

In [15]:
token_weights = (ungroupped_token_counts.mean() / ungroupped_token_counts) ** 0.1
token_weights

array([0.99353973, 1.49377596, 0.99304323, 1.42020646, 1.0546257 ,
       1.27398286, 0.81412992, 1.26206447, 0.94235489, 1.43915525,
       0.94240202, 1.56562302, 1.12994078, 1.61227144, 1.1441243 ])