# Data File Check

- data_splits.pickle
- id_to_ix_map.pickle
- token_counts.pickle

## data_splits.pickle

In [1]:
import pickle

def get_fold_data():
    with open('../data_file/data_splits.pickle', 'rb') as f:
        data_splits = pickle.load(f)
    return data_splits

data_splits = get_fold_data()

In [2]:
for key1 in data_splits.keys():
    for key2 in data_splits[key1].keys():
        for key3 in data_splits[key1][key2].keys():
            count = 0
            for fold, values in enumerate(data_splits[key1][key2][key3]):
                fold_id_list = []
                for value in values:
                    fold_id_list.append(value)
                count += len(fold_id_list)

## id_to_ix_map.pickle

In [4]:
with open('../data_file/id_to_ix_map.pickle', 'rb') as f:
    map_data = pickle.load(f)

In [9]:
map_data

{'../../../feedback-prize-2021/train/CF48D9415493.txt': 0,
 '../../../feedback-prize-2021/train/9741E87BE7CE.txt': 1,
 '../../../feedback-prize-2021/train/43B24ED85767.txt': 2,
 '../../../feedback-prize-2021/train/7C898E56E23C.txt': 3,
 '../../../feedback-prize-2021/train/EB9D8FFB4F45.txt': 4,
 '../../../feedback-prize-2021/train/F45F03EBB2CA.txt': 5,
 '../../../feedback-prize-2021/train/75BD2CB94662.txt': 6,
 '../../../feedback-prize-2021/train/5FB75CCB31F8.txt': 7,
 '../../../feedback-prize-2021/train/46527BA000FB.txt': 8,
 '../../../feedback-prize-2021/train/16585724607E.txt': 9,
 '../../../feedback-prize-2021/train/4434757F78FB.txt': 10,
 '../../../feedback-prize-2021/train/9FD65F435FD4.txt': 11,
 '../../../feedback-prize-2021/train/0F10DC1AE015.txt': 12,
 '../../../feedback-prize-2021/train/1A4DFD122114.txt': 13,
 '../../../feedback-prize-2021/train/D12A571CCFA4.txt': 14,
 '../../../feedback-prize-2021/train/4D04E578034E.txt': 15,
 '../../../feedback-prize-2021/train/D1DBB999DB47.

## token_counts.pickle

In [ ]:
import h5py
import numpy as np
from tqdm import tqdm

In [ ]:
total_token_counts = np.zeros(15, 'f8')
raw_token_counts = np.zeros(15, 'f8')
for x, y in sorted_counters:
    raw_token_counts[x] = y
    if x == 0:
        total_token_counts[0] = y
    else:
        ix = (x + 1) // 2 * 2
        total_token_counts[ix] += y total_token_counts[ix - 1] += y

raw_token_counts /= raw_token_counts.mean()

In [ ]:
f = h5py.File('../../processed_data_v0.h5py')

all_token_counts = np.zeros((15,), 'i8')

for ix in tqdm(range(len(f['tokens']) - 1)):
    targets = f['cbio_labels'][ix].argmax(-1)[1:f['num_tokens'][ix][0] - 1]
    a, b = np.unique(targets, return_counts=True)
    all_token_counts[a] += b
    
    ungroupped_token_counts = all_token_counts / all_token_counts.mean()

In [5]:
with open('../data_file/token_counts.pickle', 'rb') as f:
    groupped_token_counts, ungroupped_token_counts = pickle.load(f)

In [7]:
ungroupped_token_counts

array([ 549185.,    9305.,  551937.,   15419.,  302404.,   45702.,
       4023777.,   50206.,  932022.,   13505.,  931556.,    5817.,
        151710.,    4337.,  133918.])

In [9]:
groupped_token_counts

array([ 549185.,  561242.,  561242.,  317823.,  317823., 4069479.,
       4069479.,  982228.,  982228.,  945061.,  945061.,  157527.,
        157527.,  138255.,  138255.])

In [15]:
token_weights = (ungroupped_token_counts.mean() / ungroupped_token_counts) ** 0.1
token_weights

array([0.99353973, 1.49377596, 0.99304323, 1.42020646, 1.0546257 ,
       1.27398286, 0.81412992, 1.26206447, 0.94235489, 1.43915525,
       0.94240202, 1.56562302, 1.12994078, 1.61227144, 1.1441243 ])